# Train recipe for web 1M ship. Do not load as the main env ini.
# Sweep: maze/sweep_1787713469111_0593.ini
[base]
env_name = maze
gpu_offset = 5
run_id = web1m_maze
checkpoint_interval = 200
eval_episodes = 10000

[vec]
total_agents = 1024
num_buffers = 4
num_threads = 4
num_policies = 1
hist_policy_hidden_size = 0
hist_policy_num_layers = 0
hist_policy_percent = 0

[env]
dr = 0
num_agents = 1
num_bots = 0
num_maps = 8192
map_size = -1

[policy]
hidden_size = 256
num_layers = 4

[train]
gpus = 1
total_timesteps = 479974496
learning_rate = 0.00110763917
anneal_lr = 1
min_lr_ratio = 0
gamma = 0.994495213
gae_lambda = 0.962765336
replay_ratio = 3.55375457
clip_coef = 0.178680003
vf_coef = 1.39852107
vf_clip_coef = 2.28064823
max_grad_norm = 1.5
ent_coef = 9.12203177e-05
anneal_ent_coef = 0
min_ent_coef_ratio = 0.1
momentum = 0.993050575
minibatch_size = 32768
horizon = 128
vtrace = 0
vtrace_rho_clip = 1.0
vtrace_c_clip = 1.0
verb_eps = 0.0
verb_eps_anneal_start = 0.4
verb_eps_anneal_end = 1.0
