# Train recipe for web 1M ship. Do not load as the main env ini.
# Sweep: nmmo3/sweep_1787481846229_1117.ini
[base]
env_name = nmmo3
gpu_offset = 0
run_id = web1m_nmmo3
checkpoint_interval = 200
eval_episodes = 10000

[vec]
total_agents = 4096
num_buffers = 4
num_threads = 8
num_policies = 1
hist_policy_hidden_size = 0
hist_policy_num_layers = 0
hist_policy_percent = 0

[env]
dr = 0
num_agents = 1024
num_bots = 0
width = 512
height = 512
num_enemies = 2048
num_resources = 2048
num_weapons = 1024
num_gems = 512
tiers = 5
levels = 40
teleportitis_prob = 0.001
enemy_respawn_ticks = 2
item_respawn_ticks = 100
x_window = 7
y_window = 5
reward_combat_level = 0.689959466
reward_prof_level = 0.922388434
reward_item_level = 0.587256789
reward_market = 0.0
reward_death = -0.127605617
clear_stale_entities = 1

[policy]
hidden_size = 512
num_layers = 1

[train]
gpus = 1
total_timesteps = 723610240
learning_rate = 0.00235779677
anneal_lr = 1
min_lr_ratio = 0
gamma = 0.998546779
gae_lambda = 0.69545877
replay_ratio = 2.18575954
clip_coef = 0.196015164
vf_coef = 3.12944436
vf_clip_coef = 0.00999999978
max_grad_norm = 1.5
ent_coef = 0.00147054426
anneal_ent_coef = 0
min_ent_coef_ratio = 0.1
momentum = 0.952874541
minibatch_size = 32768
horizon = 32
vtrace = 0
vtrace_rho_clip = 1.0
vtrace_c_clip = 1.0
verb_eps = 0.0
verb_eps_anneal_start = 0.4
verb_eps_anneal_end = 1.0
checkpoint_interval = 200
