# Train recipe for web 1M ship. Do not load as the main env ini.
# Sweep: tetris/sweep_1787621818695_0753.ini
[base]
env_name = tetris
gpu_offset = 3
run_id = web1m_tetris
checkpoint_interval = 200
eval_episodes = 10000

[vec]
total_agents = 16384
num_buffers = 4
num_threads = 8
num_policies = 1
hist_policy_hidden_size = 0
hist_policy_num_layers = 0
hist_policy_percent = 0

[env]
dr = 0
num_agents = 1
num_bots = 0
n_rows = 20
n_cols = 10
use_deck_obs = 1
n_init_garbage = 4
n_noise_obs = 0

[policy]
hidden_size = 256
num_layers = 5

[train]
gpus = 1
total_timesteps = 1.13882637e+09
learning_rate = 0.00860913284
anneal_lr = 1
min_lr_ratio = 0.0
gamma = 0.998846292
gae_lambda = 0.384289861
replay_ratio = 1.64598322
clip_coef = 0.120990537
vf_coef = 0.81052351
vf_clip_coef = 0.966890097
max_grad_norm = 0.100000001
ent_coef = 0.00161809556
anneal_ent_coef = 0
min_ent_coef_ratio = 0.1
momentum = 0.84525466
minibatch_size = 32768
horizon = 256
vtrace = 0
vtrace_rho_clip = 1.0
vtrace_c_clip = 1.0
verb_eps = 0.0
verb_eps_anneal_start = 0.4
verb_eps_anneal_end = 1.0
